apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-dns-metrics-bash
  namespace: kube-system
  labels:
    application: kube-dns-metrics-bash
    version: v0.0.4
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-dns-metrics-bash
  template:
    metadata:
      labels:
        application: kube-dns-metrics-bash
        version: v0.0.4
    spec:
      priorityClassName: system-cluster-critical
      containers:
        - image: pierone.stups.zalan.do/teapot/kube-dns-metrics-bash:v0.0.5
          name: kube-dns-metrics-bash
          resources:
            limits:
              cpu: 25m
              memory: 100Mi
            requests:
              cpu: 25m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 3
            failureThreshold: 5
            successThreshold: 1
          ports:
            - containerPort: 8080
