apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
  labels:
    application: external-dns
    version: pr-876-1
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: external-dns
  template:
    metadata:
      labels:
        application: external-dns
        version: pr-876-1
      annotations:
        iam.amazonaws.com/role: "{{ .LocalID }}-app-external-dns"
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns-test:pr-876-1
        args:
        - --source=service
        - --source=ingress
        - --provider=aws
        - --registry=txt
        - --txt-owner-id={{ .Region }}:{{ .LocalID }}
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 7979
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop: ["ALL"]
