apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: skipper-ingress
  namespace: kube-system
  labels:
    application: skipper-ingress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skipper-ingress
  minReplicas: {{ $cfg.skipper_ingress_min_replicas }}
  maxReplicas: {{ $cfg.skipper_ingress_max_replicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ $cfg.skipper_ingress_target_average_utilization_cpu }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ $cfg.skipper_ingress_target_average_utilization_memory }}
