apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    application: coredns
  name: coredns
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      application: coredns
      instance: cluster-dns
