# everything defined under here will be deleted before applying the manifests
pre_apply:
  - name: cluster-dns
    namespace: kube-system
    kind: PodDisruptionBudget

# everything defined under here will be deleted after applying the manifests
post_apply: []
