# example: remove the app-ingress-controller deployment from kube-system
# pre_apply:
# - name: app-ingress-controller
#   namespace: kube-system
#   kind: deployment

# everything defined under here will be deleted before applying the manifests
pre_apply:
- name: vpa-admission-controller
  namespace: kube-system
  kind: deployment
- name: vpa-tls-certs
  namespace: kube-system
  kind: secret
- name: vpa-webhook
  namespace: kube-system
  kind: service
- name: vpa-recommender
  namespace: kube-system
  kind: deployment
- name: vpa-updater
  namespace: kube-system
  kind: deployment
- name: verticalpodautoscalers.poc.autoscaling.k8s.io
  namespace: ""
  kind: CustomResourceDefinition
- name: verticalpodautoscalercheckpoints.poc.autoscaling.k8s.io
  namespace: ""
  kind: CustomResourceDefinition
- name: vpa-webhook-config
  namespace: ""
  kind: "MutatingWebhookConfiguration"

# everything defined under here will be deleted after applying the manifests
post_apply: []
